### PR TITLE
Support strong name building and packaging

### PR DESCRIPTION
**Pull request by skarllot**
Create the strong named alternative for 'Ductus.FluentDocker' packages.

### CODE REVIEW

**Comment by mariotoffia** [comment]
I'm all for committing this. However I have a question. Is there any reason for distributing this as a separate project instead of just signing the original one and thus not having multiple assemblies doing the same thing?

**Comment by skarllot** [comment]
I thought you'd want to keep the original unsigned.

**Comment by mariotoffia** [comment]
Not at all! would you mind changing this PR to sign the original? ( and I'll release it directly)

**Comment by skarllot** [comment]
@mariotoffia Done

**Comment by skarllot** [comment]
@mariotoffia The new package (2.2.10) is ok.

I already removed the 'Ductus.FluentDocker.StrongName' package.

**Pull request merged**
