### PR TITLE
GH154: Add SourceLink support

### LINKED ISSUE #154: Add SourceLink support
[SourceLink](https://github.com/dotnet/sourcelink) is standard now and would make it easy to debug code using this great package!

From what I can see, the FluentDocker source should already be building [snupkg](https://github.com/mariotoffia/FluentDocker/blob/master/appveyor.yml#L43) files, but they don't seem be to available on [NuGet.org](https://www.nuget.org/packages/Ductus.FluentDocker)?

If you don't want to upload a separate symbols package, a popular option now is to include the portable pdb directly in the main NuGet package. This is my preference as the pdb with embedded SourceLink references is all one needs to start debugging. In order to enable that, you need to add the following property in your `csproj` (or `Directory.Build.props`):
```xml
 <AllowedOutputExtensionsInPackageBuildOutputFolder>$(AllowedOutputExtensionsInPackageBuildOutputFolder);.pdb</AllowedOutputExtensionsInPackageBuildOutputFolder>

```
then you can remove the following properties from your  `csproj` (or `Directory.Build.props`):
```xml
<IncludeSymbols>true</IncludeSymbols>
<SymbolPackageFormat>snupkg</SymbolPackageFormat>
```

### PR DESCRIPTION
**Pull request by gitfool**
Fixes #154.

Note: switches from separate `snupkg` to an embedded portable `pdb` in the main `nupkg`. Just an idea. Have a look and let me know what you think.

Also, I can't seem to build locally, so I'm pushing a PR to see if AppVeyor will build it. 😛

### CODE REVIEW

**Comment by gitfool** [comment]
@mariotoffia please review. I had to bump `GitVersionTask` to the latest beta to get the build to work.

**Comment by mariotoffia** [comment]
Many thanks for this neat contribution! :)

**Comment by gitfool** [comment]
@mariotoffia could you do me a favor and release another version so I can use it with symbols? 😉

**Comment by gitfool** [comment]
I can now debug step into prerelease version `2.7.60-beta.127`! 😃

**Pull request merged**
