### PR TITLE
Add UseNetworkWithAlias() on ContainerBuilder

### PR DESCRIPTION
**Pull request by fbraun4358**
A redo of #172 to avoid creating API incompatibilities. I mainly made a new PR because I just started from scratch and didn't want to have to deal with reworking the other branch.

I still want to add some tests but wanted to get an initial implementation down. I know the opposite of TDD 😄

### CODE REVIEW

**Comment by fbraun4358** [comment]
Should now have tests that cover all the new additions.

**Comment by mariotoffia** [comment]
@fbraun4358  Thanks for this great PR! :) -

I need to fix the build environment since it complains about "The version of Java (1.8.0_221) you have used to run this analysis is deprecated and we stopped accepting it."

When updated I'll merge this PR!

Cheers,
 Mario :)

**Comment by mariotoffia** [comment]
@fbraun4358  Can you please merge from master (?) so you'll get the new `appveyor.yml` and hence it will build porperly - then I can commit this PR.

Cheers,
 Mario :)

**Comment by fbraun4358** [comment]
@mariotoffia I got your changes merged into the branch

**Comment by mariotoffia** [comment]
@fbraun4358  thanks again for you great PR! :)

**Pull request merged**
